### ISSUE TITLE
Support inline classes for API routes

### ISSUE THREAD

**Issue by alexbezhan** [papsign/Ktor-OpenAPI-Generator#101]
Any chance do support inline classes for params? It would be good to avoid unnecessary allocations
```kotlin
    @JvmInline
    @Path("{email}")
    value class ByEmailPath(
        @PathParam("email") val email: String,
    )
```

```
API route with ByEmailPath must be a data class.
java.lang.AssertionError: API route with ByEmailPath must be a data class.
	at com.papsign.ktor.openapigen.parameters.util.UtilKt.buildParameterHandler(Util.kt:21)
	at com.papsign.ktor.openapigen.route.OpenAPIRoute.handle(OpenAPIRoute.kt:43)
	at com.papsign.ktor.openapigen.route.path.normal.NormalOpenAPIRoute.handle(NormalOpenAPIRoute.kt:36)
```

**Comment by Wicpar** [comment]
You can't do inline data classes ?

**Comment by Wicpar** [comment]
they are indee incompatible, if you want to implement them you need to add the logic to `com/papsign/ktor/openapigen/parameters/util/Util.kt`

**Comment by Wicpar** [comment]
in principle just the isData check could be removed to make it work
