### ISSUE TITLE
Deserialisation of List<UUID> in body fails during runtime

### ISSUE THREAD

**Issue by LukasForst** [papsign/Ktor-OpenAPI-Generator#112]
`post` fails to deserialise `List<UUID>` in body, even though Swagger knows that the correct type is `UUID`. Kotlin says it's `UUID`, however during runtime, it's `String`, which results in `ClassCastException` when accessing the element.

Minimal working example:
```kotlin
fun NormalOpenAPIRoute.testRoute() {
    route("/test").post<Unit, String, List<UUID>> { _, listUuids ->
        println(listUuids.joinToString(separator = " - ") { it.toString() }) // access on the element throws java.lang.ClassCastException
        respond("OK")
    }
}
```
Debugger:
![image](https://user-images.githubusercontent.com/14038818/137276195-b5ef9892-e4c2-4201-9611-2e35bae16fc6.png)

Exception:
```
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.UUID (java.lang.String and java.util.UUID are in module java.base of loader 'bootstrap')
	at com.wire.troy.routing.ConversationRoutesKt$testRoute$1$1.invoke(ConversationRoutes.kt:81)
	at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:85)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:3344)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:3361)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:3360)
```

And the `openapi.json`
```json
{
  "/test": {
    "post": {
      "requestBody": {
        "content": {
          "application/json": {
            "schema": {
              "items": {
                "format": "uuid",
                "nullable": false,
                "type": "string"
              },
              "nullable": false,
              "type": "array"
            }
          }
        }
      },
      "responses": {
        "200": {
          "content": {
            "application/json": {
              "schema": {
                "nullable": false,
                "type": "string"
              }
            }
          },
          "description": "OK"
        }
      }
    }
  }
}
```

**Comment by kkalisz** [comment]
To be honest this is not an open API generator issue. It is mostly related to generic types information erasure at runtime. Jackson can't get generic type information so it is not able to propper parse this type. This will not work for top-level generic objects. But it should be fine for such a case.
`class UuidsList(val values: List<UUID>`

But this will require changing payload from list of uuids, to object that contains a list of UUIDs

Another solution will be to use post "x-www-form-urlencoded" content type with key-value pairs. But this will look exactly the same as the previous example (UuidsList)

We can use inheritance to preserve generic type at runtime, But unfortunately, this will not work out of the box as code from DefaultCollectionSchemaProvider needs to be adjusted as for now it only handles current class generic arguments without supertype support.

`class UuidsList: ArrayList<UUID> { }`

I have created some dirty working solution 
https://github.com/kkalisz/Ktor-OpenAPI-Generator/tree/generic_parameters
https://github.com/kkalisz/Ktor-OpenAPI-Generator/blob/generic_parameters/src/test/kotlin/com/papsign/ktor/openapigen/TopLevelGenericObjectRequestTest.kt
