### ISSUE TITLE
Exception at application startup when under high volume

### ISSUE THREAD

**Issue by msramosjr** [papsign/Ktor-OpenAPI-Generator#85]
We are experiencing an error that occurs everytime at application startup, and only at application startup. An exception is thrown by the framework when doing some reflection related stuff. This happens only in our production environment, we couldn't reproduce it locally or in other environments. So we think that somehow this bug happens due to the high traffic in our production environment. (about 40k RPM)

Exception being thrown
```
java.lang.IllegalAccessException: class com.papsign.ktor.openapigen.validation.ValidationHandler$12 cannot access a member of class com.mycompany.api.GetParams with modifiers "private final" 
 at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:376) 
 at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:642) 
 at java.base/java.lang.reflect.Field.checkAccess(Field.java:1075) 
 at java.base/java.lang.reflect.Field.set(Field.java:778) 
 at com.papsign.ktor.openapigen.validation.ValidationHandler$12.invoke(ValidationHandler.kt:243) 
 at com.papsign.ktor.openapigen.validation.ValidationHandler.handle(ValidationHandler.kt:262) 
 at com.papsign.ktor.openapigen.route.OpenAPIRoute$handle$$inlined$apply$lambda$1$1.invokeSuspend(OpenAPIRoute.kt:65) 
 at com.papsign.ktor.openapigen.route.OpenAPIRoute$handle$$inlined$apply$lambda$1$1.invoke(OpenAPIRoute.kt) 
 at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:323) 
 at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:168) 
 at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:188) 
 at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:31) 
 at io.ktor.routing.Routing.executeResult(Routing.kt:147) 
 at io.ktor.routing.Routing.interceptor(Routing.kt:34) 
 at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:99) 
 at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt) 
 at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:323) 
 at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:168) 
 at io.ktor.features.ContentNegotiation$Feature$install$1.invokeSuspend(ContentNegotiation.kt:107) 
 at io.ktor.features.ContentNegotiation$Feature$install$1.invoke(ContentNegotiation.kt) 
 at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:323) 
 at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:168) 
 at io.ktor.features.StatusPages$interceptCall$2.invokeSuspend(StatusPages.kt:101) 
 at io.ktor.features.StatusPages$interceptCall$2.invoke(StatusPages.kt) 
 at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91) 
 at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:194) 
 at io.ktor.features.StatusPages.interceptCall(StatusPages.kt:100) 
 at io.ktor.features.StatusPages$Feature$install$2.invokeSuspend(StatusPages.kt:140) 
 at io.ktor.features.StatusPages$Feature$install$2.invoke(StatusPages.kt) 
 at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:323) 
 at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:168) 
 at io.ktor.metrics.micrometer.MicrometerMetrics$Feature$install$2.invokeSuspend(MicrometerMetrics.kt:195) 
 at io.ktor.metrics.micrometer.MicrometerMetrics$Feature$install$2.invoke(MicrometerMetrics.kt) 
 at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:323) 
 at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:168) 
 at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:188) 
 at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:31) 
 at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:121) 
 at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt) 
 at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:323) 
 at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:168) 
 at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:188) 
 at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:31) 
 at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invokeSuspend(NettyApplicationCallHandler.kt:40) 
 at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt) 
 at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55) 
 at kotlinx.coroutines.BuildersKt__Builders_commonKt.startCoroutineImpl(Builders.common.kt:190) 
 at kotlinx.coroutines.BuildersKt.startCoroutineImpl(Unknown Source) 
 at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:145) 
 at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56) 
 at kotlinx.coroutines.BuildersKt.launch(Unknown Source) 
 at io.ktor.server.netty.NettyApplicationCallHandler.handleRequest(NettyApplicationCallHandler.kt:30) 
 at io.ktor.server.netty.NettyApplicationCallHandler.channelRead(NettyApplicationCallHandler.kt:24) 
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) 
 at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:59) 
 at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:368) 
 at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) 
 at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) 
 at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) 
 at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) 
 at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) 
 at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) 
 at java.base/java.lang.Thread.run(Thread.java:847) 

```

GetParams code
```
data class GetParams(
    @MinLength(1) @QueryParam("accountId") val accountId: String,
    @QueryParam("status") val status: String?,
    @QueryParam("type") val type: String?,
    @QueryParam("events") val events: Boolean?
)
```

Any thoughts on this?

**Comment by Wicpar** [comment]
It looks like your security manager prevents reflection in your production environment.

**Comment by msramosjr** [comment]
Thank you for the quick reply.

I don't think this is the case for two reasons:

1) The exception occurs only a few times at startup. Aside from these few errors, our application is running normally in production.
2) We use docker in production, and I tried to reproduce the error running the exact same image locally but it doesn't happen.

Aside from that, I'll try to change val to var as a workaround.

Do still think this is a security manager issue?

**Comment by Wicpar** [comment]
Yes, as the exception originates here: https://github.com/papsign/Ktor-OpenAPI-Generator/blob/8915dfc6e8f10a3665db6bfdd09b156988eec856/src/main/kotlin/com/papsign/ktor/openapigen/validation/ValidationHandler.kt#L243

Reflection is used to set each field as there is no guarantee to be a proper constructor.
I have no idea why it might change between launches, but you can try setting the security manager explicitly.
It is possible the docker image has a way to know it is in production and set stricter rules.

**Comment by msramosjr** [comment]
Ok, I see... I'll try to set the security manager explicitly and see if this works. Thanks.

**Comment by DarkXanteR** [comment]
I also get the same error which occurs every time after starting the application and with two simultaneous requests to the same endpoint.

@msramosjr have you found a solution?

**Comment by Wicpar** [comment]
@DarkXanteR can you post the stacktraces ?

**Comment by DarkXanteR** [comment]
I have this error only when using Trim annotation.
```
java.lang.IllegalAccessException: class com.papsign.ktor.openapigen.validation.ValidationHandler$12 cannot access a member of class Minimal$FilterQuery with modifiers "private final"
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
	at java.base/java.lang.reflect.Field.checkAccess(Field.java:1075)
	at java.base/java.lang.reflect.Field.set(Field.java:778)
	at com.papsign.ktor.openapigen.validation.ValidationHandler$12.invoke(ValidationHandler.kt:243)
	at com.papsign.ktor.openapigen.validation.ValidationHandler.handle(ValidationHandler.kt:262)
	at com.papsign.ktor.openapigen.route.OpenAPIRoute$handle$$inlined$apply$lambda$1$1.invokeSuspend(OpenAPIRoute.kt:65)
	at com.papsign.ktor.openapigen.route.OpenAPIRoute$handle$$inlined$apply$lambda$1$1.invoke(OpenAPIRoute.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:183)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
	at io.ktor.routing.Routing.executeResult(Routing.kt:147)
	at io.ktor.routing.Routing.interceptor(Routing.kt:34)
	at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:99)
	at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
	at io.ktor.features.ContentNegotiation$Feature$install$1.invokeSuspend(ContentNegotiation.kt:107)
	at io.ktor.features.ContentNegotiation$Feature$install$1.invoke(ContentNegotiation.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:183)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:120)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:183)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invokeSuspend(NettyApplicationCallHandler.kt:40)
	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:111)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at io.ktor.server.netty.NettyApplicationCallHandler.handleRequest(NettyApplicationCallHandler.kt:30)
	at io.ktor.server.netty.NettyApplicationCallHandler.channelRead(NettyApplicationCallHandler.kt:24)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:59)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:368)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by msramosjr** [comment]
@DarkXanteR I still haven't solved it. But I still haven't tested @Wicpar suggestions. I'm planning on doing this by the next week.

**Comment by Wicpar** [comment]
@DarkXanteR same issue Indeed. Either use `var`, or security manager with the `suppressAccessChecks` permission.

**Comment by Wicpar** [comment]
Another possibility is to refactor the code to use the clone method and change only the relevant field and fallback to the reflection method if it doesn't exist.

**Comment by DarkXanteR** [comment]
Using `var` doesn't work because the underlying java field still `private`.


> Another possibility is to refactor the code to use the clone method and change only the relevant field and fallback to the reflection method if it doesn't exist.

Like [this](https://github.com/DarkXanteR/Ktor-OpenAPI-Generator/commit/a58b374aed2a496bd7b949d22e8a101184baa6c7)?

**Comment by Wicpar** [comment]
@DarkXanteR yes, does this fix the issue for you ?

**Comment by DarkXanteR** [comment]
@Wicpar yes

**Comment by Wicpar** [comment]
@DarkXanteR can you make a pull request ?

**Comment by msramosjr** [comment]
Great job @DarkXanteR ! @Wicpar could you please generate a new release with this fix?

**Comment by Wicpar** [comment]
done
